### PR TITLE
Feature/bluetooth architecture refactoring

### PR DESCRIPTION
**Pull request by ajdevy**

### CODE REVIEW

**Comment by rinat-enikeev** [comment]
Hi @ajdevy! 

Consider I want to write own app for Ruuvi devices from scratch. Which steps shall I do in order to reuse Ruuvi Station app Bluetooth code?

**Comment by ajdevy** [comment]
@

> Hi @ajdevy!
> 
> Consider I want to write own app for Ruuvi devices from scratch. Which steps shall I do in order to reuse Ruuvi Station app Bluetooth code?
> 
> Let's discuss in #81

You need the Interactor, Gateways, models and RuuviNotifier

**Comment by rinat-enikeev** [comment]
> @
> 
> > Hi @ajdevy!
> > Consider I want to write own app for Ruuvi devices from scratch. Which steps shall I do in order to reuse Ruuvi Station app Bluetooth code?
> > Let's discuss in #81
> 
> You need the Interactor, Gateways, models and RuuviNotifier

Is it possible to extract them to library? Keeping in mind that we need to register for permissions in Android Manifest?

**Comment by ajdevy** [comment]
> > @
> > > Hi @ajdevy!
> > > Consider I want to write own app for Ruuvi devices from scratch. Which steps shall I do in order to reuse Ruuvi Station app Bluetooth code?
> > > Let's discuss in #81
> > 
> > 
> > You need the Interactor, Gateways, models and RuuviNotifier
> 
> Is it possible to extract them to library? Keeping in mind that we need to register for permissions in Android Manifest?

Yes, it is possible.

**Comment by rinat-enikeev** [comment]
@ajdevy is the requirement for user notification handled in the current codebase? 

If I remember correctly, if you are scanning for bluetooth, you must inform user starting with SDK > 26. 

https://github.com/rinat-enikeev/BTLib/blob/master/btlib/src/main/java/io/btkit/btlib/BTScanner.kt#L71

**Comment by ajdevy** [comment]
@rinat-enikeev yes, but it still should be refactored, there are currently 3 implementations that can be made into one

**Pull request closed without merging**
