### PR TITLE
Bugfix/background service

### PR DESCRIPTION
**Pull request by ajdevy**

### CODE REVIEW

**Comment by DG12** [comment]
Could you please describe what was wrong and how you fixed it.

**Comment by rinat-enikeev** [comment]
@DG12 several bugs and major refactoring. @ajdevy can explain more.

**Comment by ajdevy** [comment]
@DG12 background scanning was not working, but it is still not working as expected for Lauri, debugging...

**Comment by DG12** [comment]
Way did you add a back gateway?

**Comment by ajdevy** [comment]
@DG12 for easy testing, also it will come handy for future unit tests

**Comment by DG12** [comment]
Good idea. Please add a comment the source. These are the kind of things that, without comments, will surely cause confusion by anyone looking at the code and may even appear extraneous in the future and cause someone to remove it. Thanks

**Pull request merged**
